############################################################
# +------------------------------------------------------+ #
# |                       Item                          | #
# +------------------------------------------------------+ #
############################################################

items:
  example-item:
    type: 'APPLE'
    price: 5
    amount: 10